

mybatis-plus:
  configuration:
    log-prefix: tb_
#    开启基础日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ssm_book
#    username: root
#    password: root
spring:
  datasource:
    #   数据源基本配置
    url: jdbc:mysql://localhost:3306/ssm_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    druid:

#
#spring:
#  datasource:
#    druid:
#     driver: com.mysql.jdbc.Driver
#     url: jdbc:mysql://127.0.0.1:3306/ssm_book
#     username: root
#     password: root